### ISSUE TITLE
Make models serializable

### ISSUE THREAD

**Issue by c-o-l-o-r** [c-o-l-o-r/DelphiAPI#4]
Check this out: https://stackoverflow.com/a/15538391

Basically we want to convert them to json so we can easily send them from the endpoint without duplicating the logic.

**Comment by c-o-l-o-r** [comment]
@alexdwu13 serialized the stake model in commit 718ee72afa3fbfa2910a0c7b05ab5c34ca77a4df. Once the other models are serialized we can simplify the logic here: 

https://github.com/c-o-l-o-r/DelphiAPI/blob/bd0891e621cb20a1a0f59fcef93e19ea453d8c97/delphi_api/app/migrations/models.py#L49-L58

To be something more like:

`claims_info = [ json.dumps(el) for el in self.claims ]`

**Comment by westonkelliher** [comment]
Use function objToJSON() in app.util.json . Be sure to pass proper arguments for `exclude` to avoid infinite recursion.
